### ISSUE TITLE
xTransects in user_input_data appear wonky

### ISSUE THREAD

**Issue by jwfiedler** [AthinaLange/UAV_automated_rectification#3]
Section xTRANSECT, starting at line 284 of user_input_data. 
Not sure if it's just me, but the x transects look like they're pointing a little too south. 
Is this just a rough guestimate rectification issue or is there something deeper happening?
<img width="1234" alt="image" src="https://github.com/AthinaLange/UAV_automated_rectification/assets/18490723/dde77122-b0f4-4829-a27a-0ba7e552765f">

**Comment by AthinaLange** [comment]
This was fixed in the latest few commits
